---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu
    driver_config:
        image: ubuntu:latest
        platform: ubuntu
  - name: centos
    driver_config:
        image: centos:latest
        platform: centos

suites:
  - name: default
    run_list:
      - recipe[chef-julianlang::default]
    attributes:
